# Generated by Django 3.2.7 on 2021-09-17 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_item',
            field=models.CharField(choices=[('Pespsi', 'Pespsi'), ('Coca Cola', 'Coca Cola')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
