# Generated by Django 3.2.7 on 2021-09-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0003_auto_20210917_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
    ]
