# Generated by Django 3.2.7 on 2021-09-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0005_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
