# Generated by Django 3.2.7 on 2021-09-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0008_auto_20210917_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
