# Generated by Django 3.2.7 on 2021-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0009_alter_order_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
