# Generated by Django 3.2.7 on 2021-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0010_alter_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.CharField(choices=[('Not done', 'Not done'), ('Done', 'Done')], default='Not done', max_length=10),
        ),
    ]
