# Generated by Django 3.2.7 on 2021-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kfc', '0011_order_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(max_length=11),
        ),
    ]
